### ISSUE TITLE
WindowBits and degree

### ISSUE THREAD

**Issue by miles-six** [matter-labs/z-prize-msm-gpu-combined#2]
The choice of the "windowbits" size is influenced by the length of the scalar or the size of the degree. In the case where the degree is very small, such as 2^13, how should "windowbits" be selected? Can you give me some advice? Thanks！！

**Comment by robik75** [comment]
Hi Miles, as mentioned on the Z-Prize discord, i suggest studying the slides here: https://www.slideshare.net/GusGutoski/multiscalar-multiplication-state-of-the-art-and-new-ideas
That should give you a general idea on how to arrive at some some ballpark number for `windowbits`.
The concrete number also depends on the concrete implementation of the algorithm, hardware, configuration parameters (like how much precomputation was used) etc., usually it is chosen by running benchmarks with different `windowbits` values and choosing the fastes one.
Please let me know if that answers your question and i can close this issue.

**Comment by miles-six** [comment]
yeah thanks
